# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    rebase-strategy: auto
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    rebase-strategy: auto
    directory: "/typescript"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    rebase-strategy: auto
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
