[workspace]
members = [
  "rust/common-builder",
  "rust/common-javascript-interpreter",
  "rust/common-macros",
  "rust/common-protos",
  "rust/common-runtime",
  "rust/common-test-fixtures",
  "rust/common-tracing",
  "rust/common-wit",
]

# See: https://github.com/rust-lang/rust/issues/90148#issuecomment-949194352
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1" }
async-stream = { version = "0.3" }
async-trait = { version = "0.1" }
axum = { version = "0.7" }
blake3 = { version = "1.5" }
boa_engine = { version = "0.19"}
boa_gc = { version = "0.19" }
boa_runtime = { version = "0.19" }
bytes = { version = "1" }
clap = { version = "4.5" }
common-builder = { path = "./rust/common-builder" }
common-javascript-interpreter = { path = "./rust/common-javasript-interpreter" }
common-macros = { path = "./rust/common-macros" }
common-protos = { path = "./rust/common-protos", default-features = false }
common-runtime = { path = "./rust/common-runtime" }
common-test-fixtures = { path = "./rust/common-test-fixtures" }
common-tracing = { path = "./rust/common-tracing" }
common-wit = { path = "./rust/common-wit" }
criterion = { version = "0.5" }
deno_emit = { version = "0.43" }
deno_graph = { version = "0.79" }
http = { version = "1.1" }
http-body-util = { version = "0.1" }
hyper-util = { version = "0.1", features = ["client", "client-legacy"] }
js-component-bindgen = { version = "1", features = ["transpile-bindgen"] }
js-sys = { version = "0.3" }
lazy_static = { version = "1" }
mime_guess = { version = "2" }
once_cell = { version = "1" }
prost = { version = "0.13" }
rand = { version = "0.8" }
redb = { version = "2" }
reqwest = { version = "0.12", default-features = false  }
rust-embed = { version = "8.4" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sieve-cache = { version = "0.2" }
tempfile = { version = "3" }
thiserror = { version = "1" }
tonic = { version = "0.12" }
tonic-build = { version = "0.12" }
tokio = { version = "1" }
tower-http = { version = "0.5" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing-log", "json"] }
tracing-web = { version = "0.1" }
url = { version = "2" }
wasm-bindgen = { version = "0.2" }
wasmtime = { version = "22" }
wasmtime-wasi = { version = "22" }
wasmtime-wasi-http = { version = "22" }
wasmtime-environ = { version = "22" }
web-sys = { version = "0.3" }
wit-bindgen = { version = "0.27" }
wit-bindgen-rt = { version = "0.27" }
wit-parser = { version = "0.212" }

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true