package common:basic@0.0.1;

interface host-callback {
  callback: func(input: string) -> result<string, string>;
}

interface processor {
  run: func(input: option<string>) -> result<option<string>, string>;
}

interface vm {
  set-source: func(source: string) -> result<_, string>;
}

world module {
  export processor;
}

world virtual-module {
  import host-callback;
  export processor;
  export vm;
}
