name: "GCP Authentication and Docker Push"
description: "Authenticate to Google Cloud, push a Docker image to Google Artifact Registry"
inputs:
  gar_region:
    description: "Google Artifact Registry region"
    required: true
  image_tags:
    description: "Docker image tags to push"
    required: true
  gcp_project_id:
    description: "Google Cloud Project ID"
    required: true
  gcp_service_account:
    description: "Google Cloud Service Account"
    required: true
  gcp_workload_identity_provider:
    description: "Google Cloud Workload Identity Provider"
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        service_account: ${{ inputs.gcp_service_account }}
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        project_id: ${{ inputs.gcp_project_id }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Check gcloud cli
      shell: bash
      run: gcloud info

    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.gar_region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Push to Google Artifact Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ inputs.image_tags }}
