[profile.default]
fail-fast = true

[profile.ci]
retries = 4
# Terminates test after waiting (`period` * `terminate-after`).
# After timeout, will still retry `retries` times.
slow-timeout = { period = "300s", terminate-after = 3 }
fail-fast = false
test-threads = 1
