name: "Nix Setup"
description: "Setup nix actions"
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        use-flakehub: false
        diagnostic-endpoint: ''