package common:module@0.0.1;

interface reflect {
  input-keys: func() -> list<string>;
  output-keys: func() -> list<string>;
}

world common {
  import common:data/types@0.0.1;
  import common:io/state@0.0.1;
  import reflect;

  export run: func() -> result<_, string>;
}