name: GCP Docker Build

on:
  workflow_dispatch:
    inputs:
      push:
        description: "Push the image to the registry"
        required: false
        default: true
        type: boolean
  push:

env:
  push: ${{ github.event.inputs.push || github.ref == 'refs/heads/main' }}
  GCP_REGION: us-central1
  REPOSITORY: "${{ github.env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REGISTRY_REPOSITORY }}"

  EXECUTION_IMAGE: debian:latest

  BASE_IMAGE_NAME: base
  BASE_IMAGE_PATH: "${{ github.env.REPOSITORY }}/${{ github.env.BASE_IMAGE_NAME }}"

  RUNTIME_IMAGE_NAME: runtime
  RUNTIME_IMAGE_PATH: "${{ github.env.REPOSITORY }}/${{ github.env.RUNTIME_IMAGE_NAME }}"

  BUILDER_IMAGE_NAME: builder
  BUILDER_IMAGE_PATH: "${{ github.env.REPOSITORY }}/${{ github.env.BUILDER_IMAGE_NAME }}"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  base:
    name: Base image
    uses: ./.github/workflows/reusable-gcp-docker-build-push.yml
    with:
      image_name: ${{ github.env.BASE_IMAGE_NAME }}
      dockerfile: ./Dockerfile
      context: .
      # push: ${{ github.event.inputs.push || github.ref == 'refs/heads/main' }}
      build_args: |
        BASE_IMAGE=${{ github.env.EXECUTION_IMAGE }}
    secrets:
      image_path: ${{ github.env.BASE_IMAGE_PATH }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

  runtime:
    name: Runtime image
    needs:
      - base
    uses: ./.github/workflows/reusable-gcp-docker-build-push.yml
    with:
      image_name: ${{ github.env.RUNTIME_IMAGE_NAME }}
      dockerfile: ./rust/Dockerfile
      context: .
      build_args: |
        BASE_IMAGE=${{ github.env.BASE_IMAGE_PATH }}
        EXECUTION_IMAGE=${{ github.env.EXECUTION_IMAGE }}
        BINARY_PATH=target/release/runtime
        FILES=target/release/runtime
        EXPOSED_PORT=8082
    secrets:
      image_path: ${{ github.env.RUNTIME_IMAGE_PATH }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

  builder:
    name: Builder image
    needs:
      - base
    uses: ./.github/workflows/reusable-gcp-docker-build-push.yml
    with:
      image_name: ${{ github.env.BUILDER_IMAGE_NAME }}
      dockerfile: ./rust/Dockerfile
      context: .
      build_args: |
        BASE_IMAGE=${{ github.env.BASE_IMAGE_PATH }}
        EXECUTION_IMAGE=${{ github.env.EXECUTION_IMAGE }}
        BINARY_PATH=target/release/builder
        FILES=target/release/builder
        EXPOSED_PORT=8082
    secrets:
      image_path: ${{ github.env.BUILDER_IMAGE_PATH }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
