name: GCP Docker Build

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  determine_build_push:
    runs-on: ubuntu-latest
    outputs:
      build_all: ${{ steps.set-vars.outputs.build_all }}
      push_images: ${{ steps.set-vars.outputs.push_images }}
    steps:
      - id: set-vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "build_all=true" >> $GITHUB_OUTPUT
            echo "push_images=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "build_all=true" >> $GITHUB_OUTPUT
            echo "push_images=false" >> $GITHUB_OUTPUT
          else
            echo "build_all=false" >> $GITHUB_OUTPUT
            echo "push_images=false" >> $GITHUB_OUTPUT
          fi

  base:
    name: Base image
    needs:
      - determine_build_push
    uses: ./.github/workflows/reusable-gcp-docker-build-push.yml
    with:
      image_name: base
      dockerfile: ./Dockerfile
      context: .
      push: ${{ needs.determine_build_push.outputs.push_images == 'true' }}
      build_args: |
        BASE_IMAGE=debian:bookworm-slim
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      repository_path: ${{ vars.GAR_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

  monolith:
    name: Monolith image
    needs:
      - base
      - determine_build_push
    uses: ./.github/workflows/reusable-gcp-docker-build-push.yml
    with:
      image_name: monolith
      dockerfile: ./rust/Dockerfile
      context: .
      push: ${{ needs.determine_build_push.outputs.push_images == 'true' }}
      build_args: |
        BASE_IMAGE=${{ vars.GAR_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/base
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      repository_path: ${{ vars.GAR_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

  runtime:
    if: needs.determine_build_push.outputs.build_all == 'true'
    name: Runtime image
    needs:
      - base
      - determine_build_push
    uses: ./.github/workflows/reusable-gcp-docker-build-push.yml
    with:
      image_name: runtime
      dockerfile: ./rust/Dockerfile
      context: .
      push: ${{ needs.determine_build_push.outputs.push_images == 'true' }}
      build_args: |
        BASE_IMAGE=${{ vars.GAR_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/base
        EXECUTION_IMAGE=debian:bookworm-slim
        BINARY_PATH=target/release/runtime
        FILES=target/release/runtime
        EXPOSED_PORT=8082
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      repository_path: ${{ vars.GAR_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

  builder:
    if: needs.determine_build_push.outputs.build_all == 'true'
    name: Builder image
    needs:
      - base
      - determine_build_push
    uses: ./.github/workflows/reusable-gcp-docker-build-push.yml
    with:
      image_name: builder
      dockerfile: ./rust/Dockerfile
      context: .
      push: ${{ needs.determine_build_push.outputs.push_images == 'true' }}
      build_args: |
        BASE_IMAGE=${{ vars.GAR_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/base
        EXECUTION_IMAGE=debian:bookworm-slim
        BINARY_PATH=target/release/builder
        FILES=target/release/builder
        EXPOSED_PORT=8082
      repository_path: ${{ vars.GAR_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
