name: Trigger auto deployment in infrastructure repo

on:
  workflow_call:
    inputs:
      builder_digest:
        required: true
        type: string
      runtime_digest:
        required: true
        type: string
      target_ref:
        required: false
        type: string
        default: main
      source_ref:
        required: true
        type: string

    secrets:
      APP_ID:
        required: true
        description: GitHub App ID
      APP_PRIVATE_KEY:
        required: true
        description: GitHub App private key
jobs:
  main:
    name: Trigger workflow_dispatch event in infrastructure repo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "system,infrastructure"

      - name: call workflow_dispatch API
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          target_ref: ${{ inputs.target_ref || 'main' }}
        run: |
          gh workflow run infrastructure-pr.yml \
            -R commontoolsinc/infrastructure \
            -f builder_digest="${{ inputs.builder_digest }}" \
            -f runtime_digest="${{ inputs.runtime_digest }}" \
            -f source_ref="${{ inputs.source_ref }}" \
            -f source_repo="${{ github.repository }}" \
            -f run_id="${{ github.run_id }}" \
            -r ${{ env.target_ref }}
