name: Trigger auto deployment in infrastructure repo

on:
  workflow_call:
    inputs:
      builder_digest:
        required: true
        type: string
      runtime_digest:
        required: true
        type: string

    secrets:
      CI_PR_PAT:
        description: "PAT for testing"
        required: true

jobs:
  main:
    name: Trigger workflow_dispatch event in infrastructure repo
    runs-on: ubuntu-latest

    steps:
      # TODO: review Github CLI
      - name: call workflow_dispatch API
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CI_PR_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/commontoolsinc/infrastructure/dispatches \
           -d '{"event_type":"auto_deploy","client_payload":{"builder_digest":"${{ inputs.builder_digest }}","runtime_digest":"${{ inputs.runtime_digest }}"}}'
