name: Sync VSCode Extensions

on:
  push:
    branches:
      - main
      - 64-create-dev-container-config
    paths:
      - ".devcontainer/devcontainer.json"
      - ".vscode/extensions.json"
      - ".github/workflows/sync-vscode-extensions.ts"
      - ".github/workflows/sync-vscode-extensions.yml"
  workflow_dispatch:

jobs:
  sync:
    name: Sync VSCode Extensions
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Sync extensions
        run: npx tsx .github/workflows/sync-vscode-extensions.ts

      - name: Check for changes
        id: git-check
        run: git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync VSCode extensions
          title: Sync VSCode extensions for ${{ github.ref_name }}
          body: |
            This PR synchronizes the VSCode extensions between `.devcontainer/devcontainer.json` and `.vscode/extensions.json` for the `${{ github.ref_name }}` branch.

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: extension-sync-${{ github.ref_name }}
          delete-branch: true
          base: ${{ github.ref_name }}
